MAX_SEQ_LEN: 600  # pois é o tamanho total do meu primeiro exemplo
EMBED_DIM: 32  # Também chamado de d_model
VOCAB_SIZE: 2000
PAD_TOKEN: 500
EOS_TOKEN: 501
N_HEADS: 4
Nx: 8  # quantas vezes vamos realimentar o bloco decoder